[package]
name = "simple-app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
axum-media = { path = "../../axum-media", features = ["urlencoded"]}
